export enum OcpiNamespace {
  Credentials = 'Credentials',
  Version = 'Version',
  Endpoint = 'Endpoint',
  Cdrs = 'Cdrs',
  OcpiTariff = 'OcpiTariff',
  ChargingProfiles = 'ChargingProfiles',
  Commands = 'Commands',
  Sessions = 'Sessions',
  OcpiTokens = 'OCPIToken',
  ClientInformation = 'ClientInformation',
  ClientCredentialsRole = 'ClientCredentialsRole',
  ServerCredentialsRole = 'ServerCredentialsRole',
  CpoTenant = 'CpoTenant',
  OcpiLocation = 'OcpiLocation',
  OcpiEvse = 'OcpiEvse',
  OcpiConnector = 'OcpiConnector',
  ResponseUrlCorrelationId = 'ResponseUrlCorrelationId',
}
