export enum OcpiNamespace {
  Credentials = 'Credentials',
  Version = 'Version',
  Endpoint = 'Endpoint',
  Cdrs = 'Cdrs',
  Tariffs = 'Tariffs',
  ChargingProfiles = 'ChargingProfiles',
  Commands = 'Commands',
  Locations = 'Locations',
  Sessions = 'Sessions',
  Tokens = 'Token',
  ClientInformation = 'ClientInformation',
  ClientCredentialsRole = 'ClientCredentialsRole',
  ServerCredentialsRole = 'ServerCredentialsRole',
  CpoTenant = 'CpoTenant',
}
