export enum ParkingType {
    ALONG_MOTORWAY = 'ALONG_MOTORWAY',
    PARKING_GARAGE = 'PARKING_GARAGE',
    PARKING_LOT = 'PARKING_LOT',
    ON_DRIVEWAY = 'ON_DRIVEWAY',
    ON_STREET = 'ON_STREET',
    UNDERGROUND_GARAGE = 'UNDERGROUND_GARAGE'
}