export enum TariffType {
    AD_HOC_PAYMENT = 'AD_HOC_PAYMENT',
    PROFILE_CHEAP = 'PROFILE_CHEAP',
    PROFILE_FAST = 'PROFILE_FAST',
    PROFILE_GREEN = 'PROFILE_GREEN',
    REGULAR = 'REGULAR',
}
