# SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
#
# SPDX-License-Identifier: Apache-2.0

name: REUSE License Check

on:
  pull_request:

jobs:
  reuse-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install REUSE tool
        run: pip install reuse

      - name: Run REUSE lint with filtering
        run: |
          # Run reuse lint and capture output
          if ! reuse lint > reuse_output.txt 2>&1; then
            echo "REUSE lint found issues. Checking against ignore list..."
            
            # Check if .reuse/ignore-files.txt exists
            if [ -f ".reuse/ignore-files.txt" ]; then
              echo "Found .reuse/ignore-files.txt file. Filtering results..."
              # Extract failing files from the REUSE output
              sed '/SUMMARY/q' reuse_output.txt | grep "^\* " | sed 's/^\* //' > failing_files.txt
              
              # Find files that are failing but NOT in the ignore list
              > unignored_failures.txt
              while IFS= read -r failing_file; do
                if [[ "$failing_file" != "reuse_output.txt" ]] && ! grep -Fxq "$failing_file" .reuse/ignore-files.txt; then
                  echo "$failing_file" >> unignored_failures.txt
                fi
              done < failing_files.txt
              
              # Check if there are any unignored failures
              if [ -s unignored_failures.txt ]; then
                echo "❌ REUSE compliance failed for the following files:"
                cat unignored_failures.txt
                echo ""
                echo "These files need proper license headers or should be added to .reuse/ignore-files.txt"
                echo ""
                exit 1
              else
                echo "✅ All REUSE lint failures are accounted for in .reuse/ignore-files.txt"
                ignored_count=$(wc -l < failing_files.txt)
                echo "Ignored $ignored_count file(s) as specified in .reuse/ignore-files.txt"
              fi
            else
              echo "❌ REUSE lint failed and no .reuse/ignore-files.txt file found"
              echo ""
              echo "Full REUSE lint output:"
              cat reuse_output.txt
              exit 1
            fi
          else
            echo "✅ REUSE lint passed - all files have proper license compliance"
          fi

      - name: Clean up temporary files
        if: always()
        run: |
          rm -f reuse_output.txt failing_files.txt unignored_failures.txt
